// writes src/build.js (not committed): the commit the code was built from, for the Debug panel. npm run build-info
const { execSync } = require('child_process'), fs = require('fs'), path = require('path');
const git = a => { try { return execSync('git ' + a, { cwd: path.join(__dirname, '..'), encoding: 'utf8' }).trim(); } catch { return ''; } };
const info = { commit: git('rev-parse --short HEAD'), branch: git('rev-parse --abbrev-ref HEAD'), date: git('log -1 --format=%cI'),
  subject: git('log -1 --format=%s').slice(0, 80), dirty: !!git('status --porcelain'), built: new Date().toISOString() };
fs.writeFileSync(path.join(__dirname, '..', 'src', 'build.js'), `// generated by tools/build-info.js\nconst BUILD = ${JSON.stringify(info)};\n`);
console.log(info.commit + (info.dirty ? ' (dirty)' : ''));
